const PROMPT_TYPE = {
  PROMPT_TEMPLATE_GENERAL: 'PROMPT_TEMPLATE_GENERAL',
  PROMPT_TEMPLATE_LOGO_DESIGN: 'PROMPT_TEMPLATE_LOGO_DESIGN',
  PROMPT_TEMPLATE_SOCIAL_MEDIA: 'PROMPT_TEMPLATE_SOCIAL_MEDIA',
  PROMPT_TEMPLATE_STOCK_IMAGE: 'PROMPT_TEMPLATE_STOCK_IMAGE',
  PROMPT_TEMPLATE_WEBSITE_DESIGN: 'PROMPT_TEMPLATE_WEBSITE_DESIGN',
} as const

export type IPromptType =
  | typeof PROMPT_TYPE.PROMPT_TEMPLATE_GENERAL
  | typeof PROMPT_TYPE.PROMPT_TEMPLATE_LOGO_DESIGN
  | typeof PROMPT_TYPE.PROMPT_TEMPLATE_SOCIAL_MEDIA
  | typeof PROMPT_TYPE.PROMPT_TEMPLATE_STOCK_IMAGE
  | typeof PROMPT_TYPE.PROMPT_TEMPLATE_WEBSITE_DESIGN

export default PROMPT_TYPE
