import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img src="https://i.ibb.co/G9DC8S0/404-2.png" />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <svg
          className="-ml-1 mr-3 h-5 w-5 animate-spin text-white"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            className="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          ></circle>
          <path
            className="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          ></path>
        </svg>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <div className="form-container">
        <div className="px-6 text-gray-900 antialiased">
          <div className="mx-auto max-w-xl divide-y py-12 md:max-w-4xl">
            <div className="py-8">
              <h1 className="text-4xl font-bold">
                @tailwindcss/forms examples
              </h1>
              <p className="mt-2 text-lg text-gray-600">
                An opinionated form reset designed to make form elements easy to
                style with utility classNamees.
              </p>
              <div className="mt-4 flex space-x-4">
                <a
                  className="text-lg underline"
                  href="https://github.com/tailwindlabs/tailwindcss-forms"
                >
                  Documentation
                </a>
                <a className="text-lg underline" href="/kitchen-sink.html">
                  Kitchen Sink
                </a>
              </div>
            </div>
            <div className="py-12">
              <h2 className="text-2xl font-bold">Unstyled</h2>
              <p className="mt-2 text-lg text-gray-600">
                This is how form elements look out of the box.
              </p>
              <div className="mt-8 max-w-md">
                <div className="grid grid-cols-1 gap-6">
                  <label className="block">
                    <span className="text-gray-700">Full name</span>
                    <input
                      type="text"
                      className="mt-1 block w-full"
                      placeholder=""
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Email address</span>
                    <input
                      type="email"
                      className="mt-1 block w-full"
                      placeholder="john@example.com"
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">When is your event?</span>
                    <input type="date" className="mt-1 block w-full" />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">
                      What type of event is it?
                    </span>
                    <select className="mt-1 block w-full">
                      <option>Corporate event</option>
                      <option>Wedding</option>
                      <option>Birthday</option>
                      <option>Other</option>
                    </select>
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Additional details</span>
                    <textarea className="mt-1 block w-full" rows={3}></textarea>
                  </label>
                  <div className="block">
                    <div className="mt-2">
                      <div>
                        <label className="inline-flex items-center">
                          <input type="checkbox" checked />
                          <span className="ml-2">
                            Email me news and special offers
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="py-12">
              <h2 className="text-2xl font-bold">Simple</h2>
              <div className="mt-8 max-w-md">
                <div className="grid grid-cols-1 gap-6">
                  <label className="block">
                    <span className="text-gray-700">Full name</span>
                    <input
                      type="text"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-gray-300
                shadow-sm
                focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50
              "
                      placeholder=""
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Email address</span>
                    <input
                      type="email"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-gray-300
                shadow-sm
                focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50
              "
                      placeholder="john@example.com"
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">When is your event?</span>
                    <input
                      type="date"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-gray-300
                shadow-sm
                focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50
              "
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">
                      What type of event is it?
                    </span>
                    <select
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-gray-300
                shadow-sm
                focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50
              "
                    >
                      <option>Corporate event</option>
                      <option>Wedding</option>
                      <option>Birthday</option>
                      <option>Other</option>
                    </select>
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Additional details</span>
                    <textarea
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-gray-300
                shadow-sm
                focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50
              "
                      rows={3}
                    ></textarea>
                  </label>
                  <div className="block">
                    <div className="mt-2">
                      <div>
                        <label className="inline-flex items-center">
                          <input
                            type="checkbox"
                            className="
                      rounded
                      border-gray-300
                      text-indigo-600
                      shadow-sm
                      focus:border-indigo-300
                      focus:ring
                      focus:ring-indigo-200
                      focus:ring-opacity-50
                      focus:ring-offset-0
                    "
                            checked
                          />
                          <span className="ml-2">
                            Email me news and special offers
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="py-12">
              <h2 className="text-2xl font-bold">Underline</h2>
              <div className="mt-8 max-w-md">
                <div className="grid grid-cols-1 gap-6">
                  <label className="block">
                    <span className="text-gray-700">Full name</span>
                    <input
                      type="text"
                      className="
                mt-0
                block
                w-full
                border-0
                border-b-2 border-gray-200 px-0.5
                focus:border-black focus:ring-0
              "
                      placeholder=""
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Email address</span>
                    <input
                      type="email"
                      className="
                mt-0
                block
                w-full
                border-0
                border-b-2 border-gray-200 px-0.5
                focus:border-black focus:ring-0
              "
                      placeholder="john@example.com"
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">When is your event?</span>
                    <input
                      type="date"
                      className="
                mt-0
                block
                w-full
                border-0
                border-b-2 border-gray-200 px-0.5
                focus:border-black focus:ring-0
              "
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">
                      What type of event is it?
                    </span>
                    <select
                      className="
                mt-0
                block
                w-full
                border-0
                border-b-2 border-gray-200 px-0.5
                focus:border-black focus:ring-0
              "
                    >
                      <option>Corporate event</option>
                      <option>Wedding</option>
                      <option>Birthday</option>
                      <option>Other</option>
                    </select>
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Additional details</span>
                    <textarea
                      className="
                mt-0
                block
                w-full
                border-0
                border-b-2 border-gray-200 px-0.5
                focus:border-black focus:ring-0
              "
                      rows={3}
                    ></textarea>
                  </label>
                  <div className="block">
                    <div className="mt-2">
                      <div>
                        <label className="inline-flex items-center">
                          <input
                            type="checkbox"
                            className="
                      border-2 border-gray-300
                      text-black
                      focus:border-gray-300 focus:ring-black
                    "
                          />
                          <span className="ml-2">
                            Email me news and special offers
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="py-12">
              <h2 className="text-2xl font-bold">Solid</h2>
              <div className="mt-8 max-w-md">
                <div className="grid grid-cols-1 gap-6">
                  <label className="block">
                    <span className="text-gray-700">Full name</span>
                    <input
                      type="text"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-transparent
                bg-gray-100
                focus:border-gray-500 focus:bg-white focus:ring-0
              "
                      placeholder=""
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Email address</span>
                    <input
                      type="email"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-transparent
                bg-gray-100
                focus:border-gray-500 focus:bg-white focus:ring-0
              "
                      placeholder="john@example.com"
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">When is your event?</span>
                    <input
                      type="date"
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-transparent
                bg-gray-100
                focus:border-gray-500 focus:bg-white focus:ring-0
              "
                    />
                  </label>
                  <label className="block">
                    <span className="text-gray-700">
                      What type of event is it?
                    </span>
                    <select
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-transparent
                bg-gray-100
                focus:border-gray-500 focus:bg-white focus:ring-0
              "
                    >
                      <option>Corporate event</option>
                      <option>Wedding</option>
                      <option>Birthday</option>
                      <option>Other</option>
                    </select>
                  </label>
                  <label className="block">
                    <span className="text-gray-700">Additional details</span>
                    <textarea
                      className="
                mt-1
                block
                w-full
                rounded-md
                border-transparent
                bg-gray-100
                focus:border-gray-500 focus:bg-white focus:ring-0
              "
                      rows={3}
                    ></textarea>
                  </label>
                  <div className="block">
                    <div className="mt-2">
                      <div>
                        <label className="inline-flex items-center">
                          <input
                            type="checkbox"
                            className="
                      rounded
                      border-transparent
                      bg-gray-200
                      text-gray-700 focus:border-transparent
                      focus:bg-gray-200
                      focus:ring-1 focus:ring-gray-500 focus:ring-offset-2
                    "
                          />
                          <span className="ml-2">
                            Email me news and special offers
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
